# yamllint disable rule:line-length
---
name: audit-dependencies
on:
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - ".cargo/audit.toml"
  workflow_dispatch:

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - name: Install `cargo-audit`
        shell: bash
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf \
            https://raw.githubusercontent.com/cargo-bins/cargo-binstall/492941711f3351597237bd85cd7320bb2a03040d/install-from-binstall-release.sh | bash
          cargo binstall --no-confirm cargo-audit cargo-deny

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run `cargo audit`
        shell: bash
        run: cargo audit

      - name: Run `cargo deny`
        shell: bash
        run: cargo deny check
